export function generateLevel1(screenWidth, screenHeight) {
  const level1EndHeight = screenHeight;

  const platforms = [
    {
      x: screenWidth / 2,
      y: level1EndHeight - 100,
      tile: "groundTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 + 150,
      y: level1EndHeight - 250,
      tile: "groundTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 - 100,
      y: level1EndHeight - 400,
      tile: "groundTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 + 120,
      y: level1EndHeight - 550,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2 - 150,
      y: level1EndHeight - 700,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 850,
      tile: "jumpTile",
      tilesCount: 7,
    },
    {
      x: screenWidth / 2 - 200,
      y: level1EndHeight - 1000,
      tile: "jumpTile",
      tilesCount: 8,
    },
    {
      x: screenWidth / 2 + 250,
      y: level1EndHeight - 1150,
      tile: "jumpTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 - 120,
      y: level1EndHeight - 1300,
      tile: "platformTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2 + 150,
      y: level1EndHeight - 1450,
      tile: "platformTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 100,
      y: level1EndHeight - 1600,
      tile: "platformTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 200,
      y: level1EndHeight - 1750,
      tile: "platformTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 1900,
      tile: "platformTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 - 150,
      y: level1EndHeight - 2050,
      tile: "dangerTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 + 100,
      y: level1EndHeight - 2200,
      tile: "jumpTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 200,
      y: level1EndHeight - 2350,
      tile: "groundTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 180,
      y: level1EndHeight - 2500,
      tile: "platformTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 2650,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2 - 170,
      y: level1EndHeight - 2800,
      tile: "jumpTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2 + 140,
      y: level1EndHeight - 2950,
      tile: "groundTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 3100,
      tile: "jumpTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 130,
      y: level1EndHeight - 3250,
      tile: "platformTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 + 200,
      y: level1EndHeight - 3400,
      tile: "dangerTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 - 110,
      y: level1EndHeight - 3550,
      tile: "jumpTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 100,
      y: level1EndHeight - 3700,
      tile: "groundTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 3850,
      tile: "platformTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 200,
      y: level1EndHeight - 4000,
      tile: "jumpTile",
      tilesCount: 7,
    },
    {
      x: screenWidth / 2 + 150,
      y: level1EndHeight - 4150,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2 - 150,
      y: level1EndHeight - 4300,
      tile: "groundTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 120,
      y: level1EndHeight - 4450,
      tile: "platformTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 4600,
      tile: "platformTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 - 100,
      y: level1EndHeight - 4750,
      tile: "jumpTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2 + 180,
      y: level1EndHeight - 4900,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2 - 130,
      y: level1EndHeight - 5050,
      tile: "jumpTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 + 160,
      y: level1EndHeight - 5200,
      tile: "groundTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 - 140,
      y: level1EndHeight - 5350,
      tile: "platformTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 200,
      y: level1EndHeight - 5500,
      tile: "jumpTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 180,
      y: level1EndHeight - 5650,
      tile: "dangerTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 5800,
      tile: "groundTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 + 150,
      y: level1EndHeight - 5950,
      tile: "platformTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2 - 110,
      y: level1EndHeight - 6100,
      tile: "jumpTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 170,
      y: level1EndHeight - 6250,
      tile: "dangerTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 - 190,
      y: level1EndHeight - 6400,
      tile: "jumpTile",
      tilesCount: 6,
    },
    {
      x: screenWidth / 2 + 100,
      y: level1EndHeight - 6550,
      tile: "platformTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 160,
      y: level1EndHeight - 6700,
      tile: "groundTile",
      tilesCount: 3,
    },
    {
      x: screenWidth / 2 + 140,
      y: level1EndHeight - 6850,
      tile: "jumpTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2,
      y: level1EndHeight - 7000,
      tile: "dangerTile",
      tilesCount: 2,
    },
    {
      x: screenWidth / 2 - 100,
      y: level1EndHeight - 7150,
      tile: "jumpTile",
      tilesCount: 4,
    },
    {
      x: screenWidth / 2 + 150,
      y: level1EndHeight - 7300,
      tile: "platformTile",
      tilesCount: 5,
    },
    {
      x: screenWidth / 2 - 150,
      y: level1EndHeight - 7450,
      tile: "groundTile",
      tilesCount: 4,
    },
  ];

  return platforms;
}
